CREATE TABLE IF NOT EXISTS BLUE_REGUSER (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME varchar(256) NOT NULL,
    SURNAME varchar(256) NOT NULL,
    EMAIL varchar(256) UNIQUE KEY NOT NULL,
	USERNAME varchar(256) UNIQUE KEY NOT NULL,
	PSWD varchar(256) NOT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp 
);
