CREATE TABLE IF NOT EXISTS BLUE_TASKLIST (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_USER bigint NOT NULL,
	STATUS int NOT NULL DEFAULT 0,
	PRIORITY int DEFAULT NULL,
	PERCENTAGE int NOT NULL DEFAULT 0,
	NAME varchar(256) NOT NULL,
    DESCRIPTION varchar(4000) DEFAULT NULL,
	TASK_OF bigint DEFAULT NULL,
	COLOR varchar(50) DEFAULT NULL,
	COLOR_ROW varchar(50) DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
	FOREIGN KEY(ID_USER) REFERENCES BLUE_REGUSER(ID)
);