CREATE TABLE IF NOT EXISTS BLUE_PREFERENCES (
	ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_USER bigint UNIQUE NOT NULL,
	PREFERENCES text DEFAULT NULL,
	INSERT_DATE timestamp NOT NULL DEFAULT current_timestamp,
	UPDATE_DATE timestamp ON UPDATE current_timestamp,
	FOREIGN KEY(ID_USER) REFERENCES BLUE_REGUSER(ID)
);